### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by Jensen0618** [CameloeAnthony/Ant#5]
Gradle 'Ant-master' project refresh failed
Error:CreateProcess error=2, 系统找不到指定的文件。

**Comment by CameloeAnthony** [comment]
@Jensen0618 直接通过clone到本地再打开工程吧。

**Comment by Jensen0618** [comment]
我是下载下来然后在Android Studio中打开的，是要用git的clone命令到本地吗？？？

**Comment by CameloeAnthony** [comment]
1 请确保git安装正确。git的path路径设置正确，可能是path路径的问题。
2 可能是gradle版本的问题。请到gradle-wrapper.properties中设置gradle版本到你自己的版本。

我刚重新下载以及clone了。都能成功运行。

**Comment by Jensen0618** [comment]
重新安装了git，可以了，目测是git的问题，谢谢。
